### ISSUE TITLE
train.py:AttributeError:"DataContainer" object has no attribute 'type'

### ISSUE THREAD

**Issue by AiQuantPro** [Wolfwjs/GANet#10]
![image](https://user-images.githubusercontent.com/32134215/167570144-0dc9e7ff-aa3a-47e2-ad6f-07a80248a61c.png)

**Comment by Wolfwjs** [comment]
Sorry for late response, I haven't encountered this problem. It looks like the `img` is not taken out of the `DataContainer`. Could you share some more info like environment and package version?

**Comment by Roserland** [comment]
I also met this problem, with the envs as below:
`TorchVision: 0.11.3+cu111
OpenCV: 4.6.0
MMCV: 0.5.6
MMDetection: 2.0.0+42bb2e4
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 11.1`

**Comment by Durobert** [comment]
@cyymt @Roserland @Wolfwjs 
I also met the problem, Did you solve it?

**Comment by dongdong2061** [comment]
I solve this problem using torch1.7.0+cuda11.0 MMCV: 0.5.6 MMDetection: 2.0.0+42bb2e4,you can refer to it

**Comment by dongdong2061** [comment]
I have solved this problem using torch1.7.0+cuda11.0 MMCV: 0.5.6 MMDetection: 2.0.0+42bb2e4,you can refer to it

**Comment by dongdong2061** [comment]
I have solved this problem using torch1.7.0+cuda11.0 MMCV: 0.5.6 MMDetection: 2.0.0+42bb2e4 and hope it is helpful for you

**Comment by AnRanbel** [comment]
> I have solved this problem using torch1.7.0+cuda11.0 MMCV: 0.5.6 MMDetection: 2.0.0+42bb2e4 and hope it is helpful for you

thanx!
