### ISSUE TITLE
can not train of the dataset i set

### ISSUE THREAD

**Issue by hyp7266** [Wolfwjs/GANet#14]
why it can train of culane ，but can not train of a small data set  builded with the same format

**Comment by hyp7266** [comment]
Do you have any requirements on the picture during the training of this code? Other codes of lane lines can be used

**Comment by Wolfwjs** [comment]
Hi, we have no special requirements for images, the annotation file annotates the (x, y) coordinates of each line. Can you describe your problem in more detail?

**Comment by lzyuan168** [comment]
Hi @Wolfwjs I have my custom dataset in this format and structure. May I know if it is the correct and required format for training.

dataset_name
|---sub_folder_1
     |---000.jpg
     |---000.lines.txt
     .
     .
     .
     |---2000.jpg
     |---2000.lines.txt

|---sub_folder_2
     |---000.jpg
     |---000.lines.txt
     .
     .
     .
     |---2000.jpg
     |---2000.lines.txt

|---list
    |---train.txt
    |---val.txt
    |---test.txt

May I know if it is necessary to have the segmentation ground truth text / image files in order for the training to run?

Thank you.
