### ISSUE TITLE
ganet_head.py

### ISSUE THREAD

**Issue by wht1712** [Wolfwjs/GANet#19]
你好，在ganet_head.py中, 你们使用了#generate root centers array from offset map parallel, 请问为什么要通过这种生成固定起点的方式去抑制一些看起来【正确】的车道线？

**Comment by spyflying** [comment]
你好，我们并没有生成固定的起点。我们选择车道线起始点的原则有两个：1）在heatmap上的置信度高于0.3；2）在offset map上到所属车道线起始点的距离小于1，也就是说，这个点所指向的车道线起始点就是它自己。我们在论文的Section3.1.3 第二段中也说明了这个过程，可以参考论文中的描述。
