### ISSUE TITLE
\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by NailinLiao** [Wolfwjs/GANet#21]
在window10 平台下运行 python setup.py develop
弹出的相关报错，显卡为桌面显卡3060，该系列显卡仅支持CUDA11以上设备，不确定导致该错误的具体原因是为何。

**Comment by Irvingao** [comment]
3060 series GPU only supports CUDA version >=11.0.
