### ISSUE TITLE
About heads in models

### ISSUE THREAD

**Issue by minhoooo1** [Wolfwjs/GANet#26]
https://github.com/Wolfwjs/GANet/blob/7378d7bd34e5d355353de3ac4961accf06b75e94/mmdet/models/dense_heads/ganet_head.py#L240

There are only offset_head and keypts_head in the paper. Why are there centerpts_head and reg_head in the code?

**Comment by spyflying** [comment]
As we mentioned in the last paragraph of Section 3.1.1, the reg_head is to predict the quantization error to avoid performance degradation and we do not include it in Figure 2 for illustration simplicity. The centerpts_head is invalid in our code. Its loss weight is set to 0 in the config file and its output is not used for lane construction. We will remove the counterpart from our code in the future version.
