### ISSUE TITLE
Auxiliary loss weight

### ISSUE THREAD

**Issue by Yibin122** [Wolfwjs/GANet#3]
I noticed 0.2 is used in your code [here](https://github.com/Wolfwjs/GANet/blob/master/configs/culane/final_exp_res18_s8.py#L26). But its set as 1.0 in paper. I guess the balancing effect of using 0.2 is better. But how different would the results be?

**Comment by 568xiaoma** [comment]
The weight of auxiliary loss have little effect on the results.
We did not conduct more experiments to investigate the effect of loss weights on the results.
