### ISSUE TITLE
Inference Upsample

### ISSUE THREAD

**Issue by isyangshu** [Wolfwjs/GANet#31]
For a resolution input of (800, 320), calculate the HeatMap on (800, 320) at inference time, and test the performance at the same size? Does performance degrade if points are directly resized to their original size? I didn't see the relevant upsampling code, I would like to ask where it is, thank you.

**Comment by Wolfwjs** [comment]
We resize the coordinates of the points by multiplying them by a scale factor. The code can be found [here](https://github.com/Wolfwjs/GANet/blob/80bfb201ce9b3006c46d75a3197d33c608543c34/tools/ganet/post_process.py#L224)
