### ISSUE TITLE
How can I get the metric results?

### ISSUE THREAD

**Issue by YuZai-SYH** [Wolfwjs/GANet#36]

**Comment by Wolfwjs** [comment]
Hi @YuZai-SYH , you can use culane's evaluation tool, please refer to this script [https://github.com/Wolfwjs/GANet/blob/master/tools/ganet/culane/lane_evaluation/eval.sh](url)

**Comment by SYH9905** [comment]
> Hi @YuZai-SYH , you can use culane's evaluation tool, please refer to this script [https://github.com/Wolfwjs/GANet/blob/master/tools/ganet/culane/lane_evaluation/eval.sh](url)

when I run the eval,sh, there is a problem：
<img width="898" alt="image" src="https://user-images.githubusercontent.com/48402247/203710963-00dde066-5283-494b-aa1a-c6aff5609677.png">
How can I solve this？ by the way， can you tell me the version of opencv you used is？
