### ISSUE TITLE
Check out the version consistency  between cudatoolkit and cuda before compiling tools

### ISSUE THREAD

**Issue by ustclbh** [Wolfwjs/GANet#4]
Hi there,  
I really appreciate your efforts on sharing the code.   I would also like to supplement a detail that might be easily ignored during compile the mmdet tools, thus leading to  **ERRORS** like 'error in deformable_col2im'  in traing procedure.  
**So double checking the version of runtime cuda version(nvcc) and  pytorch&cudatoolkit before running `python setup.py develop`.**

1. Check it out quickly:
     * Check pytorch cuda version by running `conda list | grep pytorch`. You should see pytorch  1.6.0   py3.7_**cuda10.1.243**_cudnn7.6.3_0 if following author's docementation. 
     * Then running `nvcc -V` to check version of Cuda compilation tools.  If these two are totally the same, then it should be fine. If it is not exactly the same as above then there might be problems after compling.  We tried nvcc of two versions  **V10.0.130** and **V10.1.105** on our CentOS server to complie,  in both cases it would keep throwing 'error in deformable_col2im' info during training . Though the program is still running and losses going down,  I am not sure the influence on model performance.   This is sovled by install cuda10.1.243 from [nvidia officical repo](https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Linux&target_arch=x86_64&target_distro=CentOS&target_version=7&target_type=runfilelocal). 

2. Explanation:
            Official pytorch1.6.0  is prebuilt with cuda10.1.243. It should be fine in most cases when proper cudatoolkit are installed with pytorch as long as the GPU driver installed is higher enough. But when extra cpp_extensions are needed, **we have to make sure they have to be compiled using the  runtime cuda (nvcc) of same  version of the one used by pytorch(in this case its cuda10.1.243)**. [More related discussion here](https://github.com/facebookresearch/detectron2/issues/62)

3. Some Other  Tips/Questions:
     *  **I strongly suggest adding more documentations/shell on testing shell on nromal server instead of using slurm.**
     * It should be fine in cases where servers with nvcc>10.1.243 considering downward compatibility. But it is still not sure.
     * Whether this runtime error influences the model performence is unknown.

**Comment by Wolfwjs** [comment]
Thank you very much for your detailed advice！
At present, it is recommended to use the version in the documentation. We will supplement a testing scrip soon using `torch.distributed.launch` and do more testing for the compatibility of the CUDA version.

**Comment by daeunni** [comment]
@ustclbh @Wolfwjs 

Hi, thx for your share! 
btw, my cuda version is 11.4 so it's hard to install **cuda toolkit 10.1**. 
so how can I solve this problem? 

(I was encountered `RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1595629403081/work/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8` error TT )
