### ISSUE TITLE
Hi, may I ask in which part of the code the LFA module mentioned in the paper is specifically implemented?

### ISSUE THREAD

**Issue by DaDaDalong** [Wolfwjs/GANet#41]
Hi, may I ask in which part of the code the LFA module mentioned in the paper is specifically implemented?

**Comment by Wolfwjs** [comment]
Hi @DaDaDalong , please refer here.[https://github.com/Wolfwjs/GANet/blob/8685a61fdccdf20a2846a99ba1f83135b772ba97/mmdet/models/necks/dcn_fpn.py#L285](https://github.com/Wolfwjs/GANet/blob/8685a61fdccdf20a2846a99ba1f83135b772ba97/mmdet/models/necks/dcn_fpn.py#L285)
