### ISSUE TITLE
您好，我可以问一下您mmdet2_25分支中mmcv和mmdet的版本吗？

### ISSUE THREAD

**Issue by QxGeng** [Wolfwjs/GANet#46]
您好，我可以问一下您mmdet2_25分支中mmcv和mmdet的版本吗？
我按照默认的方式安装，报错如下：
File "tools/speed_test.py", line 12, in <module>
    from mmcv import Timer
ImportError: cannot import name 'Timer' from 'mmcv'
我然后查了一下，我现在安装的mmdet是3.0.0版本，它依赖的mmcv>=2.0.0rc4。我了解到自从mmcv2.x版本开始后，就没有mmcv-full了。所以您提供的安装方法本质上有一些冲突，mmcv-full与mmdet的版本不太对得上，所以想请问下您的版本是什么

**Comment by QxGeng** [comment]
mmdet是2.25？

**Comment by Zhuyixuan519** [comment]
同询问，请问您最后是怎么解决这个呢？谢谢

**Comment by fire717** [comment]
我安装mmcv==1.7.0   mmdet==2.25.3，没有什么mm方面的报错了，但是运行训练还是有其他报错，貌似是导入DCN的时候，默认用cuda10.2编译好的，但是我这是cuda11.1....
