### ISSUE TITLE
关于GANet的一些疑问

### ISSUE THREAD

**Issue by Onehundred0906** [Wolfwjs/GANet#48]
大神 你好  最近在看您写的关于GANet的代码（MMdet2_25分支）， 在运行speed_test.py的时候发现一些无法理解的地方，分别如图所示：
1. 无法理解这里的pts_offset为什么要加上网格点的坐标，网络回归的应该就是关键点相对于起始点的偏移量？这里的偏移量与网格点相加有点不理解，麻烦解释一下呢
![3](https://github.com/Wolfwjs/GANet/assets/111262872/d05c9617-604c-4973-8bfb-fb2dcc31eb92)

2.下面两张图就是针对跑代码的时候出现的问题，就是这个字典，初始化的时候就两个键值对，然后再forward_test里面两个红框是不是你不太对呀？第三张图一下子出现4个键，这些地方是不是有问题呢？麻烦您帮忙指导一下  万分感谢
![1](https://github.com/Wolfwjs/GANet/assets/111262872/d8a4bf67-7f70-4a52-9d6f-05297798b806)
![2](https://github.com/Wolfwjs/GANet/assets/111262872/b3f177c6-c127-40e9-87e6-5c1386ace723)
![4](https://github.com/Wolfwjs/GANet/assets/111262872/65970b9d-ccdc-4b95-9168-2e545e5485c7)
如果有其他小伙伴碰到同样的问题 可以大家可以一起交流一下。

**Comment by Onehundred0906** [comment]
@Wolfwjs

**Comment by Onehundred0906** [comment]
@spyflying

**Comment by hrz2000** [comment]
回答，
1. coord_mat是根据图像尺寸构造的每个点的2d坐标，加上pts_offsets表示的是从每个点出发预测的起始点坐标，（网络回归的应该就是关键点相对于起始点的偏移量，说法是对的，在预测的时候我们不知道谁是关键点，就预测所有点相对于起始点的偏移量），然后由int_offset弥补预测数值误差，后处理的时候才找出其中的关键点。
2. tools/speed_test.py文件在编写的时候没有和模型兼容，应该在forward_test传入img_metas的时候，套一个列表model.forward_test(x,[img_metas])。img_metas在传入forward_train\forward_test的时候都是一个列表，这是mmdet的特性，列表里面是本批batch的各个元素的字典，包含了img_shape等各种keys。最后一张图只是用于测试时间的时候，这个时候不需要后处理，就没有包含太多的keys，具体在训练时候其中包含哪些keys，可以从dataset文件里面找到

**Comment by Onehundred0906** [comment]
不好意思，再打扰一下，我看了论文里写的，那个keypoint head，概率越大就容易是关键点嘛，您说的为啥子关键点在后处理的时候再确定呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hrz ***@***.***&gt;
发送时间: 2023年5月19日 17:29
收件人: Wolfwjs/GANet ***@***.***&gt;
抄送: Onehundred0906 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Wolfwjs/GANet] 关于GANet的一些疑问 (Issue #48)





 
回答，
  
coord_mat是根据图像尺寸构造的每个点的2d坐标，加上pts_offsets表示的是从每个点出发预测的起始点坐标，（网络回归的应该就是关键点相对于起始点的偏移量，说法是对的，在预测的时候我们不知道谁是关键点，就预测所有点相对于起始点的偏移量），然后由int_offset弥补预测数值误差，后处理的时候才找出其中的关键点。
 
tools/speed_test.py文件在编写的时候没有和模型兼容，应该在forward_test传入img_metas的时候，套一个列表model.forward_test(x,[img_metas])。img_metas在传入forward_train\forward_test的时候都是一个列表，这是mmdet的特性，列表里面是本批batch的各个元素的字典，包含了img_shape等各种keys。最后一张图只是用于测试时间的时候，这个时候不需要后处理，就没有包含太多的keys，具体在训练时候其中包含哪些keys，可以从dataset文件里面找到

**Comment by hrz2000** [comment]
不好意思回复稍晚，刚注意到邮件。
是的，keypointhead的输出概率越大就更可能是关键点，这是因为我们给到他的监督信号是用gt关键点做的heatmap，上次我说的“后处理的时候才找出其中的关键点”不是很准确，我想表达的是问题当中的“起始点”是通过加偏移量什么的后处理获得的（起始点是根据关键点+预测的偏移量进行聚类后处理得到的），关键点通过阈值就可以算出来（也是后处理）。

**Comment by Onehundred0906** [comment]
大佬，还是有点不明白下面图片这段代码，
这个root_center_arr这个变量是什么呢？我的理解是：我看这个变量的筛选条件就是置信度要大于0.3，并且x的offset要小于1，这不就是起始点了吗？。
但是我看到后面root_mat=coord_mat + pts_offset中，按您说的“coord_mat是根据图像尺寸构造的每个点的2d坐标，加上pts_offsets表示的是从每个点出发预测的起始点坐标”，您预测的这个pts_offsets是相对于网格点的偏差不是相对于起始点的偏差？麻烦您再帮忙解释一下哈&nbsp; 可能我绕在哪里迷糊了&nbsp; 谢谢您！


张成
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "1281503152"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 下午3:12
***@***.***&gt;;

主题:&nbsp;Re: [Wolfwjs/GANet] 关于GANet的一些疑问 (Issue #48)



不好意思，再打扰一下，我看了论文里写的，那个keypoint head，概率越大就容易是关键点嘛，您说的为啥子关键点在后处理的时候再确定呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hrz ***@***.***&gt;
发送时间: 2023年5月19日 17:29
收件人: Wolfwjs/GANet ***@***.***&gt;
抄送: Onehundred0906 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Wolfwjs/GANet] 关于GANet的一些疑问 (Issue #48)





 
回答，
  
coord_mat是根据图像尺寸构造的每个点的2d坐标，加上pts_offsets表示的是从每个点出发预测的起始点坐标，（网络回归的应该就是关键点相对于起始点的偏移量，说法是对的，在预测的时候我们不知道谁是关键点，就预测所有点相对于起始点的偏移量），然后由int_offset弥补预测数值误差，后处理的时候才找出其中的关键点。
 
tools/speed_test.py文件在编写的时候没有和模型兼容，应该在forward_test传入img_metas的时候，套一个列表model.forward_test(x,[img_metas])。img_metas在传入forward_train\forward_test的时候都是一个列表，这是mmdet的特性，列表里面是本批batch的各个元素的字典，包含了img_shape等各种keys。最后一张图只是用于测试时间的时候，这个时候不需要后处理，就没有包含太多的keys，具体在训练时候其中包含哪些keys，可以从dataset文件里面找到

**Comment by Onehundred0906** [comment]
<img width="269" alt="image" src="https://github.com/Wolfwjs/GANet/assets/111262872/ba411652-1e0e-411b-a143-ac97c93827df">

**Comment by hrz2000** [comment]
时间稍微有点长了，记忆已经开始模糊不清了，也已经错乱了😭
“这个root_center_arr这个变量是什么呢？我的理解是：我看这个变量的筛选条件就是置信度要大于0.3，并且x的offset要小于1，这不就是起始点了吗？”，不是，这个只是初步筛选，符合这些条件才有可能是关键点，后面还会在
![image](https://github.com/Wolfwjs/GANet/assets/79900945/b7089834-50a6-4587-9ec7-474e033cdc20)
后处理，里面涉及的后处理逻辑论文里面应该有讲
“按您说的“coord_mat是根据图像尺寸构造的每个点的2d坐标，加上pts_offsets表示的是从每个点出发预测的起始点坐标”，您预测的这个pts_offsets是相对于网格点的偏差不是相对于起始点的偏差？” 我们说的是一个东西，我的意思是预测是起始点相对于这个grid的偏移，根据这个偏移预测，再加上这个grid的坐标就可以得到其预测的起始点是谁，这点是比较绕的，可以先看论文理一理思路再看代码

**Comment by Onehundred0906** [comment]
好的  谢谢你哈   又看了一下论文  现在基本都懂了
