### ISSUE TITLE
How do I visualize Tusimple test set results?

### ISSUE THREAD

**Issue by dongdong2061** [Wolfwjs/GANet#50]
Hello author, thank you so much for your open source contributions. How do I visualize Tusimple test set results? I used
bash dist_test.sh tusimple final_exp_res18_s8 .. /checkpoints/ganet_tusimple_resnet18.pth --show
This command gets the test set results, but does not produce a visual picture.

**Comment by dongdong2061** [comment]
I have solved this problem.

**Comment by matthew-wave** [comment]
Hello, how did you solve this problem
