### ISSUE TITLE
why ```cpts_hm``` is not used during test?

### ISSUE THREAD

**Issue by tornadomeet** [Wolfwjs/GANet#6]
refer https://github.com/Wolfwjs/GANet/blob/master/mmdet/models/dense_heads/ganet_head.py#L286 

i run test using ```configs/culane/final_exp_res34_s8.py``` and found ```cpts``` is not used any more, but it has loss during training, why?  @Wolfwjs  thanks!

**Comment by Wolfwjs** [comment]
Currently `cpts` is indeed not used, and `cpt_loss` is 0 during training. We will update a version to remove it.

**Comment by tornadomeet** [comment]
@Wolfwjs , got it, thanks!
